# Generated by Django 3.2.12 on 2022-04-08 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password_hash', models.BinaryField(max_length=512)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=1000000)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('version', models.IntegerField()),
                ('tags', models.ManyToManyField(related_name='notes', to='app.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to='app.user')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
    ]
