# Generated by Django 3.2.12 on 2022-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
